# Generated by Django 4.1 on 2022-09-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_remove_reservation_name_remove_reservation_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
