# Generated by Django 4.1 on 2022-09-22 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0003_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='report_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 22, 17, 19, 2, 224937, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
    ]
