# Generated by Django 4.1 on 2022-09-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0004_reservation_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
