# Generated by Django 4.1 on 2022-09-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0005_alter_reservation_report_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='address',
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(default=730616855, max_length=12),
            preserve_default=False,
        ),
    ]
