# Generated by Django 4.1 on 2022-09-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0006_remove_reservation_address_reservation_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='uuid',
        ),
        migrations.AddField(
            model_name='reservation',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
