# Generated by Django 4.1 on 2022-09-22 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0008_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo_app.reservations'),
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
